apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-container
        image: 941377152740.dkr.ecr.us-east-2.amazonaws.com/ravi:10
      imagePullSecrets:
        - name: ecr-registry
